---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_linux: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: git@github.com:do3cc/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .zshrc
  - .p10k.zsh
  - .gitignore
  - .inputrc
  - .vimrc
  - .byobu
  - .tmux.conf
  - .gitconfig
  - .gitmessage.txt
  - .irssi

apt_packages:
  # for pip install python
  - build-essential
  - libffi-dev
  # stupid thing for ansible
  - cowsay
  # git
  - git
  # nice process viewer
  - htop
  # portscanner
  - nmap
  # better grep
  - silversearcher-ag
  # better tmux
  - byobu
  # newer vime
  - neovim
  # preferred shell
  - zsh
  # search through debian packages
  - apt-file
  # manage keys
  - keychain
  # IRC
  - irssi
  # nice viewer of git history
  - tig
  #  python essentials
  - python3-venv
  - python3-wheel

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
