---
- name: Install devtools
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ apt_packages }}"

- name: Ensure that a user specific bin directory exists
  file:
    path: ~/bin
    state: directory

- name: Download dein package manager installer
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: ~/bin/dein_installer.sh
    mode: '0700'
    checksum: sha256:c2ffc9e7a4ae85198391a4f27884361fa49a46474e3d92e0796a055c29c0401d
  notify:
    - install dein

- name: Ensure that the neovim config dir exists
  file:
    path: ~/.config/nvim
    state: directory

- name: Ensure that symlink for nvim to vim config exists
  file:
    src: ~/.vimrc
    dest: ~/.config/nvim/init.vim
    state: link

- name: Use zsh!
  user:
    name: do3cc
    shell: /usr/bin/zsh
  become: true
